name: Branch Name Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    uses: loadlink/.github/.github/workflows/branch-name-validation.yml@main
    with:
      branch_name: ${{ github.head_ref }}
